version: '3'
services:
  app:
    build: .
    depends_on:
      - browser
    ports:
      - 5000:5000

  browser:
    image: zenika/alpine-chrome:latest
    command: --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --no-sandbox
